import = [
    "~/.config/alacritty/themes/catppuccin-mocha.toml"
]


[shell]
program = "/bin/zsh"
args = ["-l"]

[window]
padding = { x = 5, y = 5 }
dynamic_padding = true
opacity = 0.9

[scrolling]
history = 100000
multiplier = 3

[font]
size = 14
normal = { family = "Hack Nerd Font Mono", style = "Regular" }

[keyboard]
bindings = [
{ key = "Return", mods = "Command", action = "CreateNewWindow" },
]