add_newline = false
# A minimal left prompt
format = """
$directory\
$character"""
palette = "catppuccin_mocha"
# move the rest of the prompt to the right
right_format = """
$git_branch\
$git_state\
${custom.git_status_dirty}\
$git_status\
$php\
$cmd_duration"""


#--------------------
# SYMBOLS https://starship.rs/presets/nerd-font.html
#--------------------
[aws]
symbol = "  "

[character]
success_symbol = "[❯](bold subtext1)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[directory]
read_only = " 󰌾"
style = "blue"
truncation_length = 1

[docker_context]
symbol = " "
format = "[$symbol]($style) "

[git_branch]
symbol = " "
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "bright-black"

[git_status]
format = "[($ahead_behind$stashed)]($style) "
style = "cyan"
stashed = "≡"
# format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
# style = "cyan"
# conflicted = "​"
# untracked = "​"
# modified = "​"
# staged = "​"
# renamed = "​"
# deleted = "​"
# stashed = "≡"

# https://github.com/starship/starship/issues/4927#issuecomment-1485246825
[custom.git_status_dirty]
when = 'test -n "$(git status --porcelain)"'
symbol = "*"
style = "purple"
format="[$symbol]($style) "
shell = ["bash", "--norc", "--noprofile"]

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[golang]
symbol = " "
format = "[$symbol($version)]($style) "

[hostname]
ssh_symbol = " "

[memory_usage]
symbol = "󰍛 "

[nodejs]
symbol = " "

[php]
symbol = " "
format = "[$symbol($version)]($style) "


# https://github.com/catppuccin/starship?tab=readme-ov-file
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
